Fashion/Models/FAQ.cs
namespace Fashion.Models
{
    public class FAQ
    {
        public int Id { get; set; } 
        public string Question { get; set; }
        public string answer { get; set; }
        public bool IsGeneral { get; set; }

        public bool IsRelatedToPro  { get; set; }

    }
}

Fashion/Models/Product.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Fashion.Models
{
    public class Product
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; } 
        public string ProductDescription { get; set; }
        public Features ProductFeature { get; set; }

        public int ProductPrice { get; set; }
        public int ProductQuantity { get; set; }

        public bool IspPopular { get; set; }

        public string ?ProductImg { get; set; }
        [NotMapped]

        public IFormFile ?formFile { get; set; }


        public enum Features
        {
            New, Discounted, Trending
        }

    }
}

Fashion/Areas/Administrator/Controllers/FAQsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Fashion.Data;
using Fashion.Models;

namespace Fashion.Areas.Administrator.Controllers
{
    [Area("Administrator")]
    public class FAQsController : Controller
    {
        private readonly FDbContext _context;

        public FAQsController(FDbContext context)
        {
            _context = context;
        }

        // GET: Administrator/FAQs
        public async Task<IActionResult> Index()
        {
            return View(await _context.fAQs.ToListAsync());
        }

        // GET: Administrator/FAQs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fAQ = await _context.fAQs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (fAQ == null)
            {
                return NotFound();
            }

            return View(fAQ);
        }

        // GET: Administrator/FAQs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Administrator/FAQs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Question,answer,IsGeneral,IsRelatedToPro")] FAQ fAQ)
        {
            if (ModelState.IsValid)
            {
                _context.Add(fAQ);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(fAQ);
        }

        // GET: Administrator/FAQs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fAQ = await _context.fAQs.FindAsync(id);
            if (fAQ == null)
            {
                return NotFound();
            }
            return View(fAQ);
        }

        // POST: Administrator/FAQs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Question,answer,IsGeneral,IsRelatedToPro")] FAQ fAQ)
        {
            if (id != fAQ.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(fAQ);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FAQExists(fAQ.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(fAQ);
        }

        // GET: Administrator/FAQs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fAQ = await _context.fAQs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (fAQ == null)
            {
                return NotFound();
            }

            return View(fAQ);
        }

        // POST: Administrator/FAQs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var fAQ = await _context.fAQs.FindAsync(id);
            if (fAQ != null)
            {
                _context.fAQs.Remove(fAQ);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FAQExists(int id)
        {
            return _context.fAQs.Any(e => e.Id == id);
        }
    }
}

Fashion/Areas/Administrator/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Fashion.Data;
using Fashion.Models;
using Microsoft.Extensions.Hosting;

namespace Fashion.Areas.Administrator.Controllers
{
    [Area("Administrator")]
    public class ProductsController : Controller
    {
        private readonly FDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;
        public ProductsController(FDbContext context , IWebHostEnvironment hostEnvironment)   
        {
            _context = context;
            _hostEnvironment = hostEnvironment; 
        }

        // GET: Administrator/Products
        public async Task<IActionResult> Index()
        {
            return View(await _context.Products.ToListAsync());
        }

        // GET: Administrator/Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        
        public IActionResult Create()
        {
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( Product product , IFormFile formFile)
        {
            if (ModelState.IsValid)
            {
                if (formFile != null && formFile.Length > 0)
                {
                    var wwwRootPath = _hostEnvironment.WebRootPath;

                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(formFile.FileName);

                    var path = Path.Combine(wwwRootPath, "uploads", fileName);

                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await formFile.CopyToAsync(fileStream);
                    }

                   product.ProductImg = "/uploads/" + fileName;
                }

                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

    
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,  Product product , IFormFile? formFile)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var existingproduct = await _context.Products.FindAsync(id);

                    if (existingproduct == null)
                    {
                        return NotFound();
                    }

                    if (formFile != null && formFile.Length > 0)
                    {
                        var wwwRootPath = _hostEnvironment.WebRootPath;
                        string fileName = Guid.NewGuid().ToString() + Path.GetExtension(formFile.FileName);
                        var path = Path.Combine(wwwRootPath, "uploads", fileName);

                        using (var fileStream = new FileStream(path, FileMode.Create))
                        {
                            await formFile.CopyToAsync(fileStream);
                        }

                       product.ProductImg= "/uploads/" + fileName;
                    }
                    else
                    {
                        // Retain the existing image if no new image is uploaded
                        product.ProductImg = existingproduct.ProductImg;
                    }
                    // Save the changes to the database
                    _context.Entry(existingproduct).CurrentValues.SetValues(product);
                    await _context.SaveChangesAsync();
                }
                 
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Administrator/Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Administrator/Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            if (product != null)
            {
                _context.Products.Remove(product);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ProductId == id);
        }
    }
}

Fashion/Controllers/HomeController.cs
using Fashion.Data;
using Fashion.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace Fashion.Controllers
{
    public class HomeController : Controller
    {
        private FDbContext _dbContext;
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger, FDbContext dbContext)
        {
            _logger = logger;
            _dbContext = dbContext; 
        }

        public IActionResult Index()
        {
            var products = _dbContext.Products.Take(3).ToList();

            return View(products);
        }
        public IActionResult FAQS()
        {
            return View();
        }

        public IActionResult Product()
        {
            return View();  

        }

        
        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult Story() { 
            return View(_dbContext.Employees.Include(c => c.Department).ToList());
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Fashion/ViewComponents/CustomerViewComponent.cs
using Fashion.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Fashion.ViewComponents
{
    public class CustomerViewComponent : ViewComponent
    {
        private FDbContext Db;
        public CustomerViewComponent(FDbContext _db)
        {
            Db = _db;
        }
        public IViewComponentResult Invoke()
        {
            return View(Db.Customers.Include(c => c.Department).ToList());
        }

    }
}

Fashion/ViewComponents/FAQViewComponent.cs
using Fashion.Data;
using Microsoft.AspNetCore.Mvc;

namespace Fashion.ViewComponents
{
    public class FAQViewComponent:ViewComponent
    {
        private FDbContext Db;
        public FAQViewComponent(FDbContext _db)
        {
            Db = _db;
        }
        public IViewComponentResult Invoke()
        {
            return View(Db.fAQs.ToList());
        }

    }
}

Fashion/ViewComponents/ProductViewComponent.cs
using Fashion.Data;
using Microsoft.AspNetCore.Mvc;

namespace Fashion.ViewComponents
{
    public class ProductViewComponent:ViewComponent

    {
        private FDbContext Db;
        public ProductViewComponent(FDbContext _db)
        {
            Db = _db;
        }
        public IViewComponentResult Invoke()
        {
            return View(Db.Products.OrderByDescending(x => x.ProductId).ToList());
        }
    }
}

Fashion/ViewComponents/SliderViewComponent.cs
using Fashion.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Fashion.ViewComponents
{
    public class SliderViewComponent:ViewComponent
    {
        private FDbContext Db;
        public SliderViewComponent(FDbContext _db)
        {
            Db = _db;
        }
        public IViewComponentResult Invoke()
        {
            var sliders = Db.Sliders.ToList();
            return View(sliders);
          
        }
    }
}

Fashion/Views/Home/FAQS.cshtml
@{
    ViewData["Title"] = "FAQS";
}

@await Component.InvokeAsync("FAQ")

Fashion/Views/Home/Index.cshtml
@model IEnumerable<Product>

@{
    ViewData["Title"] = "HomePage";
}



    @await Component.InvokeAsync("Slider")


<section class="front-product">
    <div class="container-fluid p-0">
        <div class="row align-items-center">

            <div class="col-lg-6 col-12">
                <img src="~/images/retail-shop-owner-mask-social-distancing-shopping.jpg" class="img-fluid" alt="">
            </div>

            <div class="col-lg-6 col-12">
                <div class="px-5 py-5 py-lg-0">

                    <h2 class="mb-4"><span>Retail</span> shop owners</h2>

                    <p class="lead mb-4">Credits go to Unsplash and FreePik websites for images used in this Little Fashion by Tooplate.</p>

                    <a asp-action="Product" asp-controller="Home" class="custom-link">
                        Explore Products
                        <i class="bi-arrow-right ms-2"></i>
                    </a>
                </div>
            </div>

        </div>
    </div>
</section>
<section class="featured-product section-padding">
    <div class="container">
        <div class="row">

            <div class="col-12 text-center">
                <h2 class="mb-5">Featured Products</h2>
            </div>
              @foreach (var item in Model)
            {
                <div class="col-lg-4 col-12 mb-3">
                    <div class="product-thumb">
                        <a href="product-detail.html">
                            <img src="@item.ProductImg" class="img-fluid product-image" alt="">
                        </a>

                        <div class="product-top d-flex">
                            <span class="product-alert me-auto">New Arrival</span>

                            <a href="#" class="bi-heart-fill product-icon"></a>
                        </div>

                        <div class="product-info d-flex">
                            <div>
                                <h5 class="product-title mb-0">
                                    <a href="product-detail.html" class="product-title-link">@item.ProductName</a>
                                </h5>

                                <p class="product-p">@item.ProductDescription</p>
                            </div>

                            <small class="product-price text-muted ms-auto mt-auto mb-5">$@item.ProductPrice</small>
                        </div>
                    </div>
                </div>
                
            }


            <div class="col-12 text-center">
                <a asp-action="Product" asp-controller="Home">View All Products</a>
            </div>
           

        </div>
    </div>
</section>

           

Fashion/Views/Home/Product.cshtml
@{
    ViewData["Title"] = "Product";
}

<header class="site-header section-padding d-flex justify-content-center align-items-center">
    <div class="container">
        <div class="row">

            <div class="col-lg-10 col-12">
                <h1>
                    <span class="d-block text-primary">Choose your</span>
                    <span class="d-block text-dark">favorite stuffs</span>
                </h1>
            </div>
        </div>
    </div>
</header>

@await Component.InvokeAsync("Product")

Fashion/Views/Home/Story.cshtml
@model IEnumerable<Employee>
@{
    ViewData["Title"] = "Story";
}





 
    <main>

    <section class="preloader">
        <div class="spinner">
            <span class="sk-inner-circle"></span>
        </div>
    </section>


        <header class="site-header section-padding-img site-header-image">
            <div class="container">
                <div class="row">

                    <div class="col-lg-6 col-12 header-info">
                        <h1>
                            <span class="d-block text-primary">Company</span>
                            <span class="d-block text-dark">Fashion</span>
                        </h1>
                    </div>
                </div>
            </div>

            <img src="~/images/header/businesspeople-meeting-office-working.jpg" class="header-image img-fluid" alt="">
        </header>

        <section class="team section-padding">
            <div class="container">
                <div class="row">

                    <div class="col-12">
                        <h2 class="mb-5">Meet our <span>team</span></h2>
                    </div>


                @foreach (var item in Model)
                {
                    <div class="col-lg-4 mb-4 col-12">
                        <div class="team-thumb d-flex align-items-center">
                            <img src="@item.EmployeeImg" class="img-fluid custom-circle-image team-image me-4" alt="">

                            <div class="team-info">
                                <h5 class="mb-0">Don</h5>
                                <strong class="text-muted">@item.Department.DepartmentName</strong>
                                <button type="button" class="btn custom-modal-btn" data-bs-toggle="modal" data-bs-target="#modal_@item.EmployeeId">
                                    <i class="bi-plus-circle-fill"></i>
                                </button>

                            </div>
                        </div>
                    </div>
                }

                </div>
            </div>
        </section>

        <section class="testimonial section-padding">
            <div class="container">
                <div class="row">

                    <div class="col-lg-9 mx-auto col-11">
                        <h2 class="text-center">Customer love, <br> <span>Little</span> Fashion</h2>

                        <div class="slick-testimonial">
                       
                            @await Component.InvokeAsync("Customer")

                        </div>
                    </div>

                </div>
            </div>
        </section>

    </main>

    @foreach (var item in Model)
{

    <div class="modal fade" id="modal_@item.EmployeeId" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg">
            <div class="modal-content border-0">
                <div class="modal-header flex-column">
                    <h3 class="modal-title" id="exampleModalLabel">@item.EmployeeName</h3>

                    <h6 class="text-muted">@item.Department.DepartmentName</h6>

                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body">
                    <h5 class="mb-4">Over three years in business had the chance to work on variety of projects, with companies</h5>

                    <div class="row mb-4">
                        <div class="col-lg-6 col-12">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        </div>

                        <div class="col-lg-6 col-12">
                            <p>Incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse commodo viverra.</p>
                        </div>
                    </div>
                    <ul class="social-icon">
                        <li class="me-3"><strong>Where to find?</strong></li>
                        <li><a href="@item.InstaUrl" class="social-icon-link bi-youtube"></a></li>
                        <li><a href="@item.LinkeUrl" class="social-icon-link bi-whatsapp"></a></li>
                        <li><a href="#" class="social-icon-link bi-instagram"></a></li>
                    </ul>
                </div>
            </div>

        </div>
    </div>

                    }